// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxLT_eiSlKc7aI7sfm1xZQIetL5gBhI4M',
    appId: '1:1088267868037:web:20f9102e843d54c6a8d6ec',
    messagingSenderId: '1088267868037',
    projectId: 'speak-safari',
    authDomain: 'speak-safari.firebaseapp.com',
    storageBucket: 'speak-safari.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgopl2Nc3u0G9yE7n0BOiPsh1I7Sm8glk',
    appId: '1:1088267868037:android:cbbe2d39292e3deda8d6ec',
    messagingSenderId: '1088267868037',
    projectId: 'speak-safari',
    storageBucket: 'speak-safari.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRQkaAr_c_I1Dwoyx777ZOk0d37b3HkTs',
    appId: '1:1088267868037:ios:eb9d1ee0d2ce9e7fa8d6ec',
    messagingSenderId: '1088267868037',
    projectId: 'speak-safari',
    storageBucket: 'speak-safari.appspot.com',
    iosClientId: '1088267868037-u2r6elbhsku0l80kk9nc798cntv590ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.speakSafari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRQkaAr_c_I1Dwoyx777ZOk0d37b3HkTs',
    appId: '1:1088267868037:ios:f7e15171ca201141a8d6ec',
    messagingSenderId: '1088267868037',
    projectId: 'speak-safari',
    storageBucket: 'speak-safari.appspot.com',
    iosClientId: '1088267868037-664adq3l4nk31vh1ev48hn3slb2jcumv.apps.googleusercontent.com',
    iosBundleId: 'com.example.speakSafari.RunnerTests',
  );
}
